import Container from "../../components/Container/Container";

export default function Dashboard() {
  return (
    <Container>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
      <div>oi</div>
    </Container>
  );
}
